spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/facechamp
    username: database_instance_username # Overwrite by `[PROJECT]/config/application.yml`. See `[PROJECT]/config/sample-application.yml`.
    password: database_instance_password # Overwrite by `[PROJECT]/config/application.yml`. See `[PROJECT]/config/sample-application.yml`.
    sql-script-encoding: UTF-8
    tomcat:
      validation-query: 'SELECT 1'
      test-while-idle: true
      test-on-borrow: true
  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      javax.persistence.sharedCache.mode: ALL
      hibernate.cache:
        use_second_level_cache: true
        use_query_cache: false
        generateStatistics: false
        region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory