facechamp:
  authorizeToken:
    secret: otp(timestamp)SigningSecretString
    ttl:    60000    # milliseconds
  jwt.token:
    secret: jwtSigningSecretString
spring:
  datasource:
    username: root
    password: ""
  jpa:
    generate-ddl: true
logging:
  level:
    facechamp: trace
    org.hibernate.SQL: debug
    org.hibernate.type: trace